name: Register Artifact
on: workflow_dispatch
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Register Artifact Custom Action
              uses: roy-ca/register-artifact-action@main
              with:
                devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
                devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
                devops-security-token: ${{ secrets.SECRET_TOKENS4 }}
                github-token: ${{ secrets.SECRET_TOKENS3 }}
                instance-url: ${{ secrets.SN_INSTANCE_URL }}
                tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
                context-github: ${{ toJSON(github) }}
                job-name: 'Register Artifact'
                artifacts: '[{"name": "com:customactiondemo1234royBasic1","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'


