name: Register Artifact
on: workflow_dispatch
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Register Artifact Custom Action
              uses: roy-ca/servicenow-devops-register-artifact@main
              with:
                devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER1 }}
                devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD1 }}
                devops-secret-token: ${{ secrets.SECRET_TOKENS5 }}
                instance-url: ${{ secrets.SN_INSTANCE_URL }}
                tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
                context-github: ${{ toJSON(github) }}
                job-name: 'Register Artifact'
                artifacts: '[{"name": "com:customactiondemo1234royBasicToken","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'


