name: Test


on:
  workflow_dispatch:
    

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build

    
  changeApproval:
    name: Register Artifact Custom Action
    needs: build
    runs-on: ubutun-latest

    steps:     
      - name: Register Artifact Custom Action
        uses: ServiceNow/servicenow-devops-register-artifact@scratch_STRY55387369
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_SECRET_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Register Artifact Custom Action'
          artifacts: '[{"name": "com:customactiondemTok5","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'
          



